### ISSUE TITLE
Repsnapper in Ubuntu 10.04 Installation fail

### ISSUE THREAD

**Issue by puixima** [timschmidt/repsnapper#41]
I have all dependences, but I can't install Repsnapper.
I've read the previous bugs, but can't find solution.
Please a need help.

This is my bug:

lucas@lucas-desktop:~/Escritorio/RepRap/RepSnapper/repsnapper$ ./autogen.sh
configure.ac:28: warning: macro `AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:28: warning: macro`AM_GLIB_GNU_GETTEXT' not found in library
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file`./config.guess'
libtoolize: copying file `./config.sub'
libtoolize: copying file`./install-sh'
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: You should add the contents of`m4/libtool.m4' to `aclocal.m4'.
libtoolize: copying file`m4/ltoptions.m4'
libtoolize: You should add the contents of `m4/ltoptions.m4' to`aclocal.m4'.
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: You should add the contents of`m4/ltsugar.m4' to `aclocal.m4'.
libtoolize: copying file`m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
libtoolize: You should add the contents of`m4/lt~obsolete.m4' to `aclocal.m4'.
libtoolize: Consider adding`-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:28: warning: macro `AM_GLIB_GNU_GETTEXT' not found in library
configure.ac:28: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1
Failed to run autoconf at ./autogen.sh line 113.

Thanks.

**Comment by davewood** [comment]
this is a mess.

installing on debian stretch because the pcsxr deb package is broken and keyboard doesnt work.

`apt install autoconf intltool libtool automake libglib2.0-dev libxml-parser-perl libgtk-3-dev libsdl2-dev`

fix windows newline in autogen.sh
```
vim autogen.sh
:%s/{Ctrl-v}{Ctrl-m}/\r/g
```

`./autogen.sh`

some stuff breaks again, so open confiure

```
vim configure
:%s/{Ctrl-v}{Ctrl-m}//g
```
at some point this error comes up
"po/Makefile.in.in was not created by intltoolize"
fix:
```
autoreconf --install
intltoolize
autoreconf
./configure
```

`make`

tried to run ./gui/pcsxr but it failed to load.

david@nbdt:~/dev/pcsxr$ ./gui/pcsxr 
Configuration file /home/david/.pcsxr/pcsxr.cfg couldn't be found
No default plugin could be found for 
No default plugin could be found for 
No default plugin could be found for 
No default plugin could be found for 
No default plugin could be found for 
No default plugin could be found for 
Picking default plugin: HLE

** (pcsxr:21791): WARNING **: Error: interface could not be loaded!



giving up
